config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :messages do
    collection do
      put "hide_sender"
      put "hide_delivered"
    end
  end
  root 'sessions#welcome'

  resource :session, only: [:new, :create, :destroy] do
    collection do
      get "welcome"
    end
  end

  resources :teams do
    collection do
      put "add_player"
      post "remove_player"
      post "add_players_from_edit"
      post "leave_team"
      post "delete_image_team"
      get "search"
    end
  end

  resources :users do
    collection do
      get 'badge'
      get 'search'
    end
  end


  resources :bookings do
    collection do
      get 'installation_options'
      get 'free_hours_table'
      get 'new_team'
      get 'new_open'
      post 'create_open'
      post 'create_team'
      get 'set_team_id'
      get 'join_team_booking'
      get 'team_bookings'
      get 'team_bookings_table'
      post 'add_team_to_existing'
      post 'delete_team_from_booking'
      post 'exit_free_booking'
    end
  end

  resources :time_bands
  resources :sports_installations

  resources :sports do
    collection do
      get 'search'
    end
  end

  resources :installations
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_and_belongs_to_many :installations, dependent: :destroy
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def search
  @sports = Sport.where("name LIKE ?", "%#{params[:name]}%")

  @teams = []

  @sports.each do |sport|
    aux = Team.where("sport_id LIKE ?", sport.id)
    aux.each do |team|
      @teams.push team
    end
  end




end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name, :max_players)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :max_players %><br>
    <%= f.number_field :max_players %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Max players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.name %></td>
        <td><%= sport.max_players %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/search.html.erb
<div class="container">
  <div class="row">
    <div class="col s6 offset-s3 mt-120">
    <%= form_tag search_sports_path, method: :get do %>
    <div class="input-field col s12">
      <%= text_field_tag :name, nil, :placeholder => "Search name sport", class: 'hidden'%>
      <%= label_tag 'Nombre', :name, data: {success: 'right'}, class: "center-align" %>
    </div>

    <div class="actions margin">
      <button class="btn waves-effect waves-light col s12 blue lighten-2" type="submit" name="action">Search
        <i class="material-icons right">info</i>
      </button>
    </div>
    <% end %>
    </div>

  </div>
  <% if @teams.length != 0 %>
      <div>
        <h3 class="center">Search</h3>
      </div>
      <table class="responsive-table striped centered mt-30">
        <thead>
        <tr>
          <th data-field="name">Name</th>
          <th data-field="sport">Sport</th>
          <th data-field="captain">Captain</th>
          <th data-field="action">Action</th>
        </tr>
        </thead>
        <% @teams.each do |team| %>
            <tr>
              <td><%=team.name%></td>
              <td><%=team.sport.name%></td>
              <td><%=team.user.name%></td>
              <td><%= link_to 'Show', team_path(team.id), class: "btn blue lighten-2" %></td>
            </tr>

        <% end %>
      </table>
  <% end %>
</div>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @sport.max_players %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>