config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :messages do
    collection do
      put "hide_sender"
      put "hide_delivered"
    end
  end
  root 'sessions#welcome'

  resource :session, only: [:new, :create, :destroy] do
    collection do
      get "welcome"
    end
  end

  resources :teams do
    collection do
      put "add_player"
      post "remove_player"
      post "add_players_from_edit"
      post "leave_team"
      post "delete_image_team"
      get "search"
    end
  end

  resources :users do
    collection do
      get 'badge'
      get 'search'
    end
  end


  resources :bookings do
    collection do
      get 'installation_options'
      get 'free_hours_table'
      get 'new_team'
      get 'new_open'
      post 'create_open'
      post 'create_team'
      get 'set_team_id'
      get 'join_team_booking'
      get 'team_bookings'
      get 'team_bookings_table'
      post 'add_team_to_existing'
      post 'delete_team_from_booking'
      post 'exit_free_booking'
    end
  end

  resources :time_bands
  resources :sports_installations

  resources :sports do
    collection do
      get 'search'
    end
  end

  resources :installations
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :sports_installation
  belongs_to :time_band
  before_save :book_time_band, :set_teams
  before_destroy :free_time_band
  after_update :book_time_band
  scope :open_team_booking, -> { where.not(local_team: -1).where(away_team: -1) }
  scope :date, -> (date) { includes(:time_band).where('date = ?', date).references(:time_band) }

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end

  def sport
    self.sports_installation.sport.name
  end

  def start_hour
    self.time_band.end_hour
  end

  def local_team_name
    Team.find(self.local_team).name
  end

  def end_hour
    self.time_band.start_hour
  end

  def free_time_band
    SportsInstallationsTimeBand.where(time_band_id: self.time_band_id, sports_installation_id: self.sports_installation_id).first.update(free: true)
  end

  def book_time_band
    SportsInstallationsTimeBand.where(time_band_id: self.time_band_id, sports_installation_id: self.sports_installation_id).first.update(free: false)
  end

  def set_teams
    self.local_team ||= -1
    self.away_team ||= -1
  end

  private :free_time_band, :book_time_band, :set_teams

end

app/controllers/bookings_controller.rb
require 'date'
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :delete_team_from_booking, :exit_free_booking ]
  before_action :authenticate
  before_action :owned, only: [:edit]

  def index
    @bookings = current_user.bookings
    @team_bookings = current_user_team_bookings
  end

  def current_user_team_bookings
    team_bookings = []
    current_user.teams.pluck(:id).each do |team_id|
      team_bookings.concat(Booking.where(away_team: team_id))
    end
    return team_bookings
  end

  def show
  end

  def new
    @booking = Booking.new
    @sports = Sport.all
  end

  def new_team
    @booking = Booking.new
    @sports = Sport.all
    render :new
  end


  def new_open
      @booking = Booking.new
      @sports = Sport.all
      render create_open_bookings_path
  end

  def edit
  end

  def create
    if new_booking_params_sended?
      sport_installation = SportsInstallation.where(sport_id: params[:sport], installation_id: params[:installation]).first
      @booking = current_user.bookings.new(sports_installation_id: sport_installation.id, time_band_id: params[:time_band_id], max_size: 0)
      if @booking.save
        redirect_to bookings_path, notice: "Booking was successfully created"
      else
        redirect_to :new
      end
    else
      redirect_to new_booking_path, alert: "Make you sure you have selected a sport, a installation and a time band..."
    end
  end

  def exit_free_booking
    participants = @booking.participants.split(',')
    if @booking.user_id == current_user.id
      @booking.destroy
      respond_to do |format|
        format.html { redirect_to bookings_path, notice: 'Booking was destroyed.' }
        format.json { head :no_content }
      end
    else
      participants.delete(current_user.dni)
      @booking.update(participants: participants.join(','))
      respond_to do |format|
        format.html { redirect_to bookings_path, notice: 'You were succesfully removed from the booking.' }
        format.json { head :no_content }
      end
    end
  end

  def update
    time_band_id = @booking.time_band_id
    respond_to do |format|
      if new_booking_params_sended? && @booking.update(time_band_id: params[:time_band_id])
        SportsInstallationsTimeBand.where(time_band_id: time_band_id, sports_installation_id: @booking.sports_installation_id).first.update(free: true)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, notice: "Make you sure you have selected a sport, a installation and a time band..." }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_team
    if new_team_booking_params_sent?
      sport_installation = SportsInstallation.where(sport_id: params[:sport], installation_id: params[:installation]).first
      @booking = current_user.bookings.new(sports_installation_id: sport_installation.id, time_band_id: params[:time_band_id], local_team: params[:team_id], max_size: 0)
      if @booking.save
        redirect_to bookings_path, notice: "Team Booking was successfully created"
      else
        redirect_to :new
      end
    else
      redirect_to new_team_bookings_path, alert: "Make you sure you have selected a sport, a installation, a team and a time band..."
    end
  end

  def create_open
    if new_booking_params_sended?
      sport_installation = SportsInstallation.where(sport_id: params[:sport], installation_id: params[:installation]).first
      @booking = current_user.bookings.new(sports_installation_id: sport_installation.id, time_band_id: params[:time_band_id], local_team: params[:team_id], max_size: Sport.find_by_id(params[:sport]).max_players, participants: "#{current_user.dni}")
      if @booking.save
        redirect_to bookings_path, notice: "Open Booking was successfully created"
      else
        redirect_to :new
      end
    else
      redirect_to new_open_bookings_path, alert: "Make you sure you have selected a sport, a installation,  and a time band..."
    end
  end


  def set_team_id
    respond_to do |format|
      format.js
    end
  end

  def join_team_booking
    @sports = Sport.all
  end

  def add_team_to_existing
    if add_team_to_existing_booking_params_sent?
      Booking.find(params[:booking_id]).update(away_team: params[:team_id])
      redirect_to bookings_path, notice: "Your team was successfully added to the booking..."
    else
      redirect_to join_team_booking_bookings_path, alert: "Make you sure you have selected a booking and a team..."
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def installation_options
    @installations = Sport.find_by_id(params[:sport_id]).installations
    respond_to do |format|
      format.js
    end
  end

  def free_hours_table
    @time_bands = SportsInstallation.where(installation_id: params[:installation_id], sport_id: params[:sport_id]).first.time_bands.where(date: extract_date_from_params)
    @sports_installation = SportsInstallation.where(installation_id: params[:installation_id], sport_id: params[:sport_id]).first
    respond_to do |format|
      format.js
    end
  end

  def delete_team_from_booking
    if @booking.local_team != -1
      if current_user.id == Team.find_by_id(@booking.local_team).user_id
        @booking.destroy
        respond_to do |format|
          format.html { redirect_to bookings_path, notice: 'Booking was  destroyed.' }
          format.json { head :no_content }
        end
      end
    else
      if @booking.away_team != -1
        if current_user.id == Team.find_by_id(@booking.away_team).user_id
          @booking.update(away_team: -1)
          respond_to do |format|
            format.html { redirect_to bookings_url, notice: 'Your team was succesfully removed from the booking.' }
            format.json { head :no_content }
          end
        end
      end
    end
  end

  def team_bookings
    @sports_installation = SportsInstallation.where(installation_id: params[:installation_id], sport_id: params[:sport_id]).first
    @team_bookings = Booking.open_team_booking.where(sports_installation: @sports_installation).where.not(user: current_user).date(extract_date_from_params)
    respond_to do |format|
      format.js
    end
  end

  def extract_date_from_params
    return Date.new(params[:date].split(",")[1].to_i, Date::MONTHNAMES.index(params[:date].split(",")[0].split(" ")[1]).to_i, params[:date].split(",")[0].split(" ")[0].to_i)
  end

  def new_booking_params_sended?
    return (params[:date] and params[:sport] != "" and params[:installation] != "" and params[:time_band_id]) ? true : false
  end

  def new_team_booking_params_sent?
    return new_booking_params_sended? && (params[:team_id] != "")
  end

  def add_team_to_existing_booking_params_sent?
    params[:booking_id] != "" && params[:team_id] != ""
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:sports_installation, :time_band)
  end

  def owned
    if @booking.owned_by?(current_user)
      true
    else
      redirect_to bookings_path, alert: "You don't own the requested booking."
      false
    end
  end

  protected :extract_date_from_params, :new_booking_params_sended?, :new_team_booking_params_sent?, :new_team_booking_params_sent?, :owned
  private :set_booking
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<% if false %>
    <%= form_for(@booking) do |f| %>
        <% if @booking.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

              <ul>
                <% @booking.errors.full_messages.each do |message| %>
                    <li>
                      <% message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :sports_installation %><br>
          <%= f.number_field :sports_installation %>
        </div>
        <div class="field">
          <%= f.label :time_band %><br>
          <%= f.number_field :time_band %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% end %>

<%= form_tag params[:action] == "new" ? bookings_path : create_team_bookings_path, novalidate: true do %>

    <div class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <%= select_tag "sport", options_from_collection_for_select(@sports, "id", "name"), prompt: "Choose a sport", required: true %>
          <label for="sport">Sport</label>
        </div>
        <div class="input-field col s6 installation">
          <%= select_tag "installation", options_from_collection_for_select(Installation.all, "id", "name"), class: "installation", prompt: "Choose a installation", required: true %>
          <label for="installation">Installation</label>
        </div>
      </div>
    </div>

    <div class="col s12">
      <div class="row">
        <div class="input-field col s12 m5">
          <input name="date" id="date" type="date" class="datepicker" required>
          <label for="date">Date</label>
          <button class="col s3 btn waves-effect waves-light" type="submit" name="action">Book!
            <i class="material-icons right">send</i>
          </button>
          <% if params[:action] == "new_team" %>
              <a class="col s7 offset-s1 waves-effect waves-light btn modal-trigger" href="#select_team">Select Team</a>
              <!--<button type="button" data-target="select_team" class="col s7 offset-s1 waves-effect waves-light btn modal-trigger">Select your team</button>-->
          <% end %>
        </div>
        <div class="col s12 col m7" id="free_hours_table">
        </div>
      </div>
    </div>
    <input type="hidden" id="time_band_id" name="time_band_id">
    <input type="hidden" id="team_id" name="team_id">
<% end %>


<div id="select_team" class="modal blue lighten-3">
  <div class="modal-content blue lighten-3">
    <h4>Select your team</h4>
    <%= select_tag "teams", options_from_collection_for_select(current_user.teams, "id", "name"), prompt: "Choose your team", required: true %>
    <label for="teams">My teams</label>
  </div>
  <div class="modal-footer blue lighten-3">
    <%= link_to "Ok", set_team_id_bookings_path, class: "modal-action modal-close waves-effect waves-green btn-flat", remote: true %>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
  </div>
</div>


<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    $('.modal-trigger').leanModal();
    $("#sport").on("change", function () {
      if ($('#sport').children(":selected").attr("value")) {
        $.ajax({
          url: "/bookings/installation_options",
          method: "GET",
          data: {
            sport_id: $('#sport').children(":selected").attr("value")
          }
        });
      }
    });

    $('.datepicker').pickadate({
      selectMonths: false, // Creates a dropdown to control month
      selectYears: false, // Creates a dropdown of 15 years to control year
      min: new Date()
    });

    function free_hours_request() {
      $.ajax({
        url: "/bookings/free_hours_table",
        type: "GET",
        data: {
          date: $("#date").val(),
          sport_id: $('#sport').children(":selected").attr("value"),
          installation_id: $('#installation').children(":selected").attr("value")
        }
      });
    }

    $("#date").on("change", function () {
      if ($('#installation').children(":selected").attr("value") && $('#sport').children(":selected").attr("value")) {
        free_hours_request();
      }
    });

    function clearDate() {
      $("#free_hours_table").html("");
      $("#date").val("");
    }

    $("#sport").on("change", clearDate);
    $('select').material_select();
  });
</script>

app/views/bookings/_free_hours_table.html.erb
<h4>Time Bands <i class="material-icons">av_timer</i></h4>
<table class="striped highlight centered responsive-table">
  <thead class="">
  <tr>
    <th data-field="id">Start Hour</th>
    <th data-field="name">End Hour</th>
    <th data-field="price">Price</th>
    <th data-field="price">Booked</th>
  </tr>
  </thead>

  <tbody>
  <%= content_tag_for(:tr, @time_bands) do |time_band| %>
      <% (time_band.date == Date.today) && (DateTime.strptime(time_band.start_hour, '%H:%M') < Time.now) ? next : false %>
      <td><%= time_band.start_hour %></td>
      <td><%= time_band.end_hour %></td>
      <td>15 €</td>
      <% if SportsInstallationsTimeBand.where(sports_installation_id: @sports_installation.id, time_band_id: time_band.id).first.free %>
          <td>
            <%= link_to "javascript:void(0)", id: time_band.id, class: "btn-floating btn-large waves-effect waves-light add_booking" do %>
                <i class="material-icons left">library_add</i>
                <span>Free</span>
            <% end %>
          </td>
      <% else %>
          <td><a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">lock</i></a></td>
      <% end %>
  <% end %>
  </tbody>
</table>

<script !src="">
  $(".add_booking").on("click", function () {

    if ($("#" + $(this).attr("id") + " i").html() == "library_add") {
      $("#time_band_id").val($(this).attr("id"));
      $("#" + $(this).attr("id") + " i").html("done");
      $("#" + $(this).attr("id") + " span").html("ok");
      $(".selected_book i").html("library_add");
      $(".selected_book span").html("free");
      $(".selected_book").removeClass("selected_book");
      $(this).addClass("selected_book");
    } else if ($("#" + $(this).attr("id") + " i").html() == "done") {
      $("#time_band_id").val("");
      $("#" + $(this).attr("id") + " i").html("library_add");
      $("#" + $(this).attr("id") + " span").html("free");
      $(this).removeClass("selected_book")
    }

  });
</script>

</div>

app/views/bookings/_installations_select.html.erb
<div class="input-field col s6 installation">
  <%= select_tag "installation", options_from_collection_for_select(@installations, "id", "name"), class: "installation", prompt: "Choose a installation", required: true %>
  <label for="installation">Installation</label>
  <script !src="">
    $("#installation").on("change", function () {
      $("#free_hours_table").html("");
      $("#date").val("");
    });
  </script>
</div>

app/views/bookings/edit.html.erb
<%= form_tag booking_path, method: :put, novalidate: true do %>

    <div class="container">
      <h1>Editing Booking</h1>
      <table class="bordered centered highlighted responsive-table">
        <thead>
        <tr>
          <th data-field="id">Sport</th>
          <th data-field="name">Sport Installation</th>
          <th data-field="price">Date</th>
          <th data-field="price">Start Hour</th>
          <th data-field="price">End Hour</th>
          <th data-field="price">Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= @booking.sports_installation.sport.name %></td>
          <td><%= @booking.sports_installation.installation.name %></td>
          <td><%= @booking.time_band.date %></td>
          <td><%= @booking.time_band.start_hour %></td>
          <td><%= @booking.time_band.end_hour %></td>
          <td>15 €</td>
        </tr>
        </tbody>
      </table>
    </div>

    <%= hidden_field_tag "sport", @booking.sports_installation.sport.id %>
    <%= hidden_field_tag "installation", @booking.sports_installation.installation.id %>

    <br>

    <div class="container">
      <div class="row">
        <div class="input-field col s12 m5">
          <input name="date" id="date" type="date" class="datepicker" required>
          <label for="date">Date</label>
          <button class="col s3 btn waves-effect waves-light" type="submit" name="action">Book!
            <i class="material-icons right">send</i>
          </button>
        </div>
        <div class="col s12 col m7" id="free_hours_table">
        </div>
      </div>
      <%= link_to 'Back', bookings_path %> |
      <%= link_to 'Show', @booking %>
      <input type="hidden" id="time_band_id" name="time_band_id">
    </div>
<% end %>


<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    $('.modal-trigger').leanModal();


    $('.datepicker').pickadate({
      selectMonths: false, // Creates a dropdown to control month
      selectYears: false, // Creates a dropdown of 15 years to control year
      min: new Date()
    });

    function free_hours_request() {
      $.ajax({
        url: "/bookings/free_hours_table",
        type: "GET",
        data: {
          date: $("#date").val(),
          sport_id: $('#sport').val(),
          installation_id: $('#installation').val()
        }
      });
    }

    $("#date").on("change", function () {
      if ($('#installation').val() && $('#sport').val()) {
        free_hours_request();
      }
    });

    function clearDate() {
      $("#free_hours_table").html("");
      $("#date").val("");
    }

    $('select').material_select();
  });
</script>

app/views/bookings/free_hours_table.js.erb
$("#free_hours_table").html("<%= j render "free_hours_table" %>");

app/views/bookings/index.html.erb
<div class="container">
  <!-- <p id="notice"><%= notice %></p> -->

  <h1 class="center-align hide-on-med-and-down title">Listing Bookings</h1>
  <h4 class="center-align hide-on-large-only title">Listing Bookings</h4>

  <table class="responsive-table">
    <thead>
    <tr>
      <th>Installation</th>
      <th>Time band</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.sports_installation.installation.name %></td>
          <td><%= booking.time_band.date %> <%= booking.time_band.start_hour %>-<%= booking.time_band.end_hour %></td>
          <td><%= link_to 'Show', booking, class: "btn blue lighten-2" %></td>
          <td><%= link_to 'Edit', edit_booking_path(booking), class: "btn blue lighten-2" %></td>
          <td><%= link_to 'Destroy', booking, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn red darken-1" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <h1 class="center-align mt-120 hide-on-med-and-down title">Team Bookings</h1>
  <h4 class="center-align mt-120 hide-on-large-only title">Team Bookings</h4>

  <table class="responsive-table">
    <thead>
    <tr>
      <th>Sports installation</th>
      <th>Time band</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @team_bookings.each do |booking| %>
        <tr>
          <td><%= booking.sports_installation %></td>
          <td><%= booking.time_band %></td>
          <td><%= link_to 'Show', booking, class: "btn blue lighten-2" %></td>
          <% if booking.owned_by?(current_user) %>
              <td><%= link_to 'Edit', edit_booking_path(booking), class: "btn blue lighten-2" %></td>
              <td><%= link_to 'Destroy', booking, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn red darken-1" %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Booking', new_booking_path, class: "btn light-blue darken-1" %>

</div>

app/views/bookings/installation_options.js.erb
$(".installation").replaceWith("<%= j render "installations_select" %>");
$('select').material_select();
$("#installation").on("change", function() {
  $("#free_hours_table").html("");
  $("#date").val("");
});

app/views/bookings/join_team_booking.html.erb
<div class="container mt-30">
  <h1>Join Team Booking</h1>
  <%= form_tag add_team_to_existing_bookings_path, novalidate: true do %>

      <div class="col s12">
        <div class="row">
          <div class="input-field col s6">
            <%= select_tag "sport", options_from_collection_for_select(@sports, "id", "name"), prompt: "Choose a sport", required: true %>
            <label for="sport">Sport</label>
          </div>
          <div class="input-field col s6 installation">
            <%= select_tag "installation", options_from_collection_for_select(Installation.all, "id", "name"), class: "installation", prompt: "Choose a installation", required: true %>
            <label for="installation">Installation</label>
          </div>
        </div>
      </div>

      <div class="col s12">
        <div class="row">
          <div class="input-field col s12 m5">
            <input name="date" id="date" type="date" class="datepicker" required>
            <label for="date">Date</label>
            <button class="col s3 btn waves-effect waves-light" type="submit" name="action">Book!
              <i class="material-icons right">send</i>
            </button>
            <button data-target="select_team" class="col s7 offset-s1 waves-effect waves-light btn modal-trigger">Select
              your team
            </button>
          </div>
          <div class="col s12 col m7" id="team_bookings_table">
          </div>
        </div>
      </div>
      <input type="hidden" id="booking_id" name="booking_id">
      <input type="hidden" id="team_id" name="team_id">
  <% end %>

  <div id="select_team" class="modal blue lighten-3">
    <div class="modal-content blue lighten-3">
      <h4>Select your team</h4>
      <%= select_tag "teams", options_from_collection_for_select(Team.where(user_id: current_user.id), "id", "name"), required: true %>
      <label for="teams">My teams</label>
    </div>
    <div class="modal-footer blue lighten-3">
      <%= link_to "Ok", set_team_id_bookings_path, class: "modal-action modal-close waves-effect waves-green btn-flat", remote: true %>
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {

    $("#sport").on("change", function () {
      if ($('#sport').children(":selected").attr("value")) {
        $.ajax({
          url: "/bookings/installation_options",
          method: "GET",
          data: {
            sport_id: $('#sport').children(":selected").attr("value")
          }
        });
      }
    });

    $('.datepicker').pickadate({
      selectMonths: false, // Creates a dropdown to control month
      selectYears: false, // Creates a dropdown of 15 years to control year
      min: new Date()
    });

    function team_booking_request() {
      $.ajax({
        url: "/bookings/team_bookings",
        type: "GET",
        data: {
          date: $("#date").val(),
          sport_id: $('#sport').children(":selected").attr("value"),
          installation_id: $('#installation').children(":selected").attr("value")
        }
      });
    }

    $("#date").on("change", function () {
      if ($('#installation').children(":selected").attr("value") && $('#sport').children(":selected").attr("value")) {
        team_booking_request();
      }
    });

    function clearDate() {
      $("#team_bookings_table").html("");
      $("#date").val("");
    }

    $("#sport").on("change", clearDate);
    $('select').material_select();
  });
</script>

app/views/bookings/new.html.erb
<div class="container mt-30">

  <% if params[:action] == "new" %>
      <h1 class="center-align">New Booking</h1>
  <% else %>
      <h1 class="center-align">New Team Booking</h1>
  <% end %>

  <%= render 'form' %>

</div>

app/views/bookings/set_team_id.js.erb
$("#team_id").val($('#teams').children(":selected").attr("value"));
$('.lean-overlay').remove();

app/views/bookings/show.html.erb
<div class="container">
  <div class="row col s12">
    <div class="col s12 valign-wrapper mt-30">

      <table class="highlight responsive-table">
        <thead>
        <tr>
          <th data-field="sport">Sport Installation</th>
          <th data-field="icon"><i class="blue-text material-icons">today</i></th>
          <th data-field="icon0"><i class="blue-text material-icons">query_builder</i></th>
        </tr>
        </thead>

        <tbody>
        <tr>
          <td><%= Installation.find_by_id(@booking.sports_installation.installation_id).name %></td>
          <td><%= @booking.time_band.date %></td>
          <td> <%= @booking.time_band.start_hour %> to  <%= @booking.time_band.end_hour %></td>
        </tr>
        </tbody>
      </table>
    </div>
    <div>
      <div class="col s12 m6">
        <% if @booking.local_team != -1 %>
            <ul class="collection">
              <li class="collection-item center-align"><h5 class="center-align">Local Team</h5></li>
              <% Team.find_by_id(@booking.local_team).users.each do |member| %>
                  <li class="collection-item avatar">
                    <%= link_to member do %>
                        <%= image_tag member.image.url(:thumb), class: "circle" %>
                    <% end %>
                    <p class="collection-item"><%= member.name %></p>
                  </li>
              <% end %>
            </ul>
        <% end %>
        <% if @booking.local_team != -1 %>
            <% if current_user.id == Team.find_by_id(@booking.local_team).user_id %>
                <%= link_to 'Remove team from booking', delete_team_from_booking_bookings_path(id: @booking.id), style: "margin-bottom: 5px", method: :post, class: "btn red col s12 m6 ", data: {confirm: 'Are you sure? The booking will be removed.'} %>
            <% end %>
        <% end %>
      </div>
      <div class="col s12 m6">
        <% if @booking.away_team != -1 %>
            <ul class="collection">
              <li class="collection-item center-align"><h5 class="center-align">Away Team</h5></li>
              <% Team.find_by_id(@booking.away_team).users.each do |member| %>
                  <li class="collection-item avatar">
                    <%= link_to member do %>
                        <%= image_tag member.image.url(:thumb), class: "circle" %>
                    <% end %>
                    <p class="collection-item"><%= member.name %></p>
                  </li>
              <% end %>
            </ul>
        <% end %>
        <% if @booking.away_team != -1 %>
            <% if current_user.id == Team.find_by_id(@booking.away_team).user_id %>
                <%= link_to 'Remove team from booking', delete_team_from_booking_bookings_path(id: @booking.id), style: "margin-bottom: 5px", method: :post, class: "btn red col s12 m6", data: {confirm: 'Team removed'} %>
            <% end %>
        <% end %>
        <br>
        <br>
      </div>
    </div>
    <% if @booking.max_size > 0 %>
        <ul class="collection with-header col s10 offset-s1 valign mt-30">
          <li class="collection-header"><h4>Participants:</h4></li>
          <% @booking.participants.split(',').each do |participant| %>
              <!--href to user profile-->
              <div>
                <li class="collection-item col s12">
                  <!--link to user profile-->
                  <row>
                    <%= link_to User.find_by_dni(participant).name, user_path(User.find_by_dni(participant)) %>
                    <% if User.find_by_dni(participant) == current_user %>
                        <%= link_to '<i class="black-text material-icons icon-trf ">delete</i>'.html_safe, exit_free_booking_bookings_path(id: @booking.id), method: :post, data: {confirm: 'Are you sure?'}, class: "secondary-content" %>
                    <% end %>
                  </row>
                  <div class="divider col s12">
                  </div>
                </li>
              </div>
          <% end %>
    <% end %>
    </ul>
    <div class="center-align col s12">
      <row class="col s12 valign">
          <%= link_to 'Edit', edit_booking_path(@booking), class: "btn blue lighten-2 s5", style: "margin-bottom: 5px" unless !@booking.owned_by?(current_user) %>
          <%= link_to 'Back', bookings_path, class: "btn blue lighten-2 s6", style: "margin-bottom: 5px" %>
      </row>
    </div>
  </div>
</div>

app/views/bookings/team_bookings.js.erb
<% if @team_bookings.length > 0 %>
  $("#team_bookings_table").html("<%= j render "team_bookings_table" %>");
  $('.modal-trigger').leanModal();
<% else %>
  $("#team_bookings_table").html("<h3>There is no teams booking for the selected date</h3>");
<% end %>