config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :messages do
    collection do
      put "hide_sender"
      put "hide_delivered"
    end
  end
  root 'sessions#welcome'

  resource :session, only: [:new, :create, :destroy] do
    collection do
      get "welcome"
    end
  end

  resources :teams do
    collection do
      put "add_player"
      post "remove_player"
      post "add_players_from_edit"
      post "leave_team"
      post "delete_image_team"
      get "search"
    end
  end

  resources :users do
    collection do
      get 'badge'
      get 'search'
    end
  end


  resources :bookings do
    collection do
      get 'installation_options'
      get 'free_hours_table'
      get 'new_team'
      get 'new_open'
      post 'create_open'
      post 'create_team'
      get 'set_team_id'
      get 'join_team_booking'
      get 'team_bookings'
      get 'team_bookings_table'
      post 'add_team_to_existing'
      post 'delete_team_from_booking'
      post 'exit_free_booking'
    end
  end

  resources :time_bands
  resources :sports_installations

  resources :sports do
    collection do
      get 'search'
    end
  end

  resources :installations
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :bookings, dependent: :destroy
  has_many :users_teams
  has_many :messages
  has_many :comments
  has_many :teams, :through => :users_teams
  has_attached_file :image, styles: {large: "600*600>", medium: "300x300>", thumb: "125x125>"}, default_url: "/default_profile.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.authenticate(dni, password)
    user = find_by_dni(dni)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.password == encrypt(password)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    access_denied unless @user == current_user
  end

  def badge
    @user = current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @users = User.where("name LIKE ?", "%#{params[:name]}%")
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:dni, :name, :password, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col s3 offset-s2">
      <%= form_for(@user, html: {multipart: true}) do |f| %>
          <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this team from being saved:</h2>

                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="input-field">
            <%= f.label :dni %><br>
            <%= f.text_field :dni %>
          </div>

          <div class="input-field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>

          <div class="input-field">
            <%= f.label :password %><br>
            <%= f.text_field :password %>
          </div>

          <div class="center-align" id="buttons_zone">
            <div class="field">
              <%= f.file_field :image, id: "user_image", style: "display: none" %>
              <a id="triggerFile" class="waves-effect waves-light btn"><i class="material-icons left">picture_in_picture</i>Image</a>
            </div>
            <br><br>
            <div class="actions">
              <button class="btn waves-effect waves-light blue lighten-1" type="submit" name="action">
                <%= f.submit %>
              </button>
            </div>
          </div>
          <br/>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('#triggerFile').on('click', function (e) {
      e.preventDefault();
      $("#user_image").trigger('click');
    });
  });
</script>

app/views/users/badge.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <%= image_tag @user.image.url(:large) %>
          <span class="card-title">Card Title</span>
        </div>
        <div class="card-content">
          <p>Dni:
            <b>
              <%= @user.dni %>
            </b>
          </p>
          <p>
            Name:
            <b>
              <%= @user.name %>
            </b>
          </p>
        </div>
        <div class="card-action">
          <%= link_to "Edit", edit_user_path(id: @user.id), class: "btn button blue blue-light-2"%>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Back', :back, class: "button btn blue blue-lighten-2" %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="col s8 offset-s2">Editing User</h1>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Dni</th>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.dni %></td>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
    <div class="col s6 offset-s3 mt-120">
    <%= form_tag search_users_path, method: :get do %>
    <div class="input-field col s12">
      <%= text_field_tag :name, nil, :placeholder => "Search name user", class: 'hidden'%>
      <%= label_tag 'Nombre', :Name, data: {success: 'right'}, class: "center-align" %>
    </div>

    <div class="actions margin">
      <button class="btn waves-effect waves-light col s12 blue lighten-2" type="submit" name="action">Search
        <i class="material-icons right">perm_identity</i>
      </button>
    </div>
    <% end %>
    </div>
  </div>

  <% if @users.length != 0 %>
<div class="row">
  <table class="responsive-table striped centered col s6 offset-s3 mt-30">
    <thead>
    <tr>
      <th data-field="name">Name</th>
    </tr>
    </thead>
    <% @users.each do |user| %>
        <tr>
          <td><%=user.name%></td>
          <td><%= link_to 'Show', user_path(user.id), class: "btn blue lighten-2" %></td>
        </tr>

    <% end %>
  </table>
  </div>
      <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <%= image_tag @user.image.url(:large) %>
          <span class="card-title">Card Title</span>
        </div>
        <div class="card-content">
          <p>Dni:
            <b>
              <%= @user.dni %>
            </b>
          </p>
          <p>
            Name:
            <b>
              <%= @user.name %>
            </b>
          </p>
        </div>
        <div class="card-action">
          <%= link_to "Edit", edit_user_path(user: @user.dni), class: "btn button blue blue-light-2" unless @user != current_user %>
          <%= link_to "Contact", new_message_path(user: @user.dni), class: "btn button blue blue-light-2" %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Back', :back, class: "button btn blue blue-lighten-2" %>
</div>