config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :messages do
    collection do
      put "hide_sender"
      put "hide_delivered"
    end
  end
  root 'sessions#welcome'

  resource :session, only: [:new, :create, :destroy] do
    collection do
      get "welcome"
    end
  end

  resources :teams do
    collection do
      put "add_player"
      post "remove_player"
      post "add_players_from_edit"
      post "leave_team"
      post "delete_image_team"
      get "search"
    end
  end

  resources :users do
    collection do
      get 'badge'
      get 'search'
    end
  end


  resources :bookings do
    collection do
      get 'installation_options'
      get 'free_hours_table'
      get 'new_team'
      get 'new_open'
      post 'create_open'
      post 'create_team'
      get 'set_team_id'
      get 'join_team_booking'
      get 'team_bookings'
      get 'team_bookings_table'
      post 'add_team_to_existing'
      post 'delete_team_from_booking'
      post 'exit_free_booking'
    end
  end

  resources :time_bands
  resources :sports_installations

  resources :sports do
    collection do
      get 'search'
    end
  end

  resources :installations
end

app/views/layouts/_modals.html.erb
<% if flash[:notice] %>
    <div id="modal" class="modal blue lighten-4">
      <div class="modal-content">
        <h4>Information</h4>
        <p> <%= flash[:notice] %></p>
      </div>
      <div class="modal-footer blue lighten-4">
        <a href="#!" class="blue  lighten-1 modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
      </div>
    </div>
<% elsif flash[:alert] %>
    <div id="modal" class="modal red lighten-3">
      <div class="modal-content">
        <h4>Errors</h4>
        <p> <%= flash[:alert] %></p>
      </div>
      <div class="modal-footer red lighten-3">
        <a href="#!" class=" red lighten-1 modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
      </div>
    </div>
<% end %>

<% if flash[:alert] || flash[:notice] %>
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
        $('#modal').openModal();
      });
    </script>
<% end %>

app/views/layouts/_navbar.html.erb
<% if current_user %>
<ul id="bookings_dropdown" class="dropdown-content">
  <li><%= link_to "My bookings", bookings_path %></li>
  <li><%= link_to "New open booking", new_open_bookings_path %></li>
  <li><%= link_to "New booking", new_booking_path %></li>
  <li><%= link_to "New team booking", new_team_bookings_path %></li>
  <li class="divider"></li>
</ul>
<ul id="team_dropdown" class="dropdown-content">
  <li><%= link_to "My Teams", teams_path %></li>
  <li><%= link_to "Join Team Booking", join_team_booking_bookings_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Create team", new_team_path %></li>
</ul>
<ul id="messages_dropdown" class="dropdown-content  ">
  <li><%= link_to "New message", new_message_path %></li>
  <li><%= link_to "Messages", messages_path %></li>
</ul>
<ul id="search_dropdown" class="dropdown-content  ">
  <li><%= link_to "Search User", search_users_path %></li>
  <li><%= link_to "Search by Sport", search_sports_path %></li>
</ul>

<nav class="blue">
  <div class="nav-wrapper">
    <%= link_to image_tag("mysb_logo_8.png"), bookings_path, class: "brand-logo" %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Installations", sports_installations_path %></li>
      <li>
        <a class="dropdown-button" href="#!" data-activates="team_dropdown">Team<i class="material-icons right">arrow_drop_down</i></a>
      </li>
      <li><%= link_to "Profile", badge_users_path %></li>
      <li>
        <a class="dropdown-button" href="#!" data-activates="messages_dropdown">Messages<i class="material-icons right">arrow_drop_down</i></a>
      </li>
      <li>
        <a class="dropdown-button" href="#!" data-activates="bookings_dropdown">Bookings<i class="material-icons right">arrow_drop_down</i></a>
      </li>

      <li>
        <a class="dropdown-button" href="#!" data-activates="search_dropdown">Search<i class="material-icons right">arrow_drop_down</i></a>
      </li>

      <li>
        <%= link_to "#" do %>
        <i onclick="search()" class="material-icons">search</i>
        <% end %>
      </li>

      <li class="search hide">
        <%= form_tag search_teams_path, method: :get do %>
        <%= text_field_tag :name, nil, :placeholder => "Search name Sport", class: 'hidden'%>
        <% end %>
      </li>

      <li>
        <%= link_to session_path, method: :delete do %>
        <i class="material-icons">settings_power</i>
        <% end %>
      </li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "My bookings", bookings_path %></li>
      <li><%= link_to "New open booking", new_open_bookings_path %></li>
      <li><%= link_to "New booking", new_booking_path %></li>
      <li><%= link_to "New team booking", new_team_bookings_path %></li>
      <li><%= link_to "My Teams", teams_path %></li>
      <li><%= link_to "Create team", new_team_path %></li>
      <li><%= link_to "Join Team Booking", join_team_booking_bookings_path %></li>
      <li><%= link_to "New message", new_message_path %></li>
      <li><%= link_to "Messages", messages_path %></li>
      <li><%= link_to "Search User", search_users_path %></li>
      <li><%= link_to "Search by Sport", search_sports_path %></li>
    </ul>
  </div>
</nav>

<script type="text/javascript" charset="utf-8">
$(document).ready(function () {
  $(".dropdown-button").dropdown();
  $(".button-collapse").sideNav();
});
function search(){
  $(".search").toggleClass('hide show');
}
</script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsBooking</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>


<%= render 'layouts/navbar' %>

<div class="my_container">
  <%= yield %>
</div>

<%= render "layouts/modals" %>
</body>
</html>